Repository ISPP-Grupo-10/cocemfe-sevilla, pull requests merged in 2024-04, with the labels that each got.

#214 Test/212 test arreglo de test de professional
  .github/workflows/django.yml
  README.md
  cocemfe_sevilla/professionals/tests.py
  cocemfe_sevilla/requirements.txt
Labels: bug, test, Grupo 3

#241 Feature/240 Añadido Backend Edición Contraseña
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/templates/update_password.html
  cocemfe_sevilla/professionals/tests.py
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
Labels: feature, Grupo 3

#246 fix: Solucionado problema tests Closes #244
  cocemfe_sevilla/authentication/__init__.py
  cocemfe_sevilla/base/__init__.py
  cocemfe_sevilla/chat_messages/__init__.py
  cocemfe_sevilla/documents/__init__.py
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/organizations/__init__.py
  cocemfe_sevilla/organizations/tests.py
  cocemfe_sevilla/professionals/__init__.py
  cocemfe_sevilla/professionals/tests.py
  cocemfe_sevilla/suggestions/__init__.py
  cocemfe_sevilla/votings/__init__.py
Labels: bug, Grupo 3

#249 Feature/248 frontend edicion contrasenya
  cocemfe_sevilla/authentication/__init__.py
  cocemfe_sevilla/base/__init__.py
  cocemfe_sevilla/chat_messages/__init__.py
  cocemfe_sevilla/documents/__init__.py
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/organizations/__init__.py
  cocemfe_sevilla/organizations/tests.py
  cocemfe_sevilla/professionals/__init__.py
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/templates/professional_data.html
  cocemfe_sevilla/professionals/templates/professional_list.html
  cocemfe_sevilla/professionals/templates/update_password.html
  cocemfe_sevilla/professionals/tests.py
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
  cocemfe_sevilla/suggestions/__init__.py
  cocemfe_sevilla/votings/__init__.py
Labels: feature, Grupo 3

#256 feat: Añade validación de emails #250
  cocemfe_sevilla/fixtures/professionals.json
  cocemfe_sevilla/professionals/models.py
  cocemfe_sevilla/professionals/templates/email/verification_email.html
  cocemfe_sevilla/professionals/templates/professional_list.html
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/utils.py
  cocemfe_sevilla/professionals/views.py
  cocemfe_sevilla/requirements.txt
Labels: feature, Grupo 3

#265 feat: Añadido de botón de editar perfil
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/professionals/views.py
Labels: feature, Grupo 3

#276 fix: correos de profesionales unicos - Closes #275
  cocemfe_sevilla/professionals/forms.py
Labels: bug, Grupo 3, URGENTE

#268 Feature/126 mapa
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
  cocemfe_sevilla/maps/admin.py
  cocemfe_sevilla/maps/apps.py
  cocemfe_sevilla/maps/migrations/__init__.py
  cocemfe_sevilla/maps/models.py
  cocemfe_sevilla/maps/templates/maps_index.html
  cocemfe_sevilla/maps/tests.py
  cocemfe_sevilla/maps/urls.py
  cocemfe_sevilla/maps/views.py
  cocemfe_sevilla/requirements.txt
Labels: feature

#279 Feature/272 fix problems subgroup 3
  cocemfe_sevilla/authentication/urls.py
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/models.py
  cocemfe_sevilla/professionals/tests.py
  cocemfe_sevilla/professionals/utils.py
  cocemfe_sevilla/professionals/views.py
  cocemfe_sevilla/static/css/chat.css
  cocemfe_sevilla/static/css/professional.css
Labels: bug, Grupo 3

#282 Feature/125 calendario
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/base/templates/user_dashboard.html
  cocemfe_sevilla/calendars/admin.py
  cocemfe_sevilla/calendars/apps.py
  cocemfe_sevilla/calendars/forms.py
  cocemfe_sevilla/calendars/migrations/__init__.py
  cocemfe_sevilla/calendars/models.py
  cocemfe_sevilla/calendars/templates/create_event.html
  cocemfe_sevilla/calendars/templates/eventos.html
  cocemfe_sevilla/calendars/tests.py
  cocemfe_sevilla/calendars/urls.py
  cocemfe_sevilla/calendars/views.py
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/documents/views.py
Labels: feature

#289 Feature/233 correcciones funcionalidad
  cocemfe_sevilla/chat_messages/templates/list_comments.html
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/documents/templates/update_pdf.html
  cocemfe_sevilla/documents/templates/upload_pdf.html
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/organizations/models.py
  cocemfe_sevilla/organizations/templates/create_organization.html
  cocemfe_sevilla/organizations/templates/organization_details.html
  cocemfe_sevilla/organizations/templates/organizations_list.html
  cocemfe_sevilla/organizations/templates/update_organization.html
  cocemfe_sevilla/organizations/views.py
  cocemfe_sevilla/professionals/models.py
  cocemfe_sevilla/professionals/templates/professional_create.html
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/professionals/templates/professional_details.html
  cocemfe_sevilla/professionals/templates/professional_list.html
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
  cocemfe_sevilla/static/css/list_pdf.css
  cocemfe_sevilla/static/css/view_pdf.css
  cocemfe_sevilla/suggestions/models.py
Labels: feature

#291 Hotfix/290 bug fallo en edición de documentos
  cocemfe_sevilla/calendars/models.py
  cocemfe_sevilla/calendars/templates/eventos.html
  cocemfe_sevilla/documents/templates/update_pdf.html
  cocemfe_sevilla/documents/views.py
Labels: bug

#288 Feature/283 boton eliminar cuenta
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
Labels: feature

#309 fix: Solucionado problema inicio sesion Closes #301
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/templates/email/verification_email.html
  cocemfe_sevilla/professionals/views.py
Labels: bug, Grupo 3

#308 feat: Actualiza Chat con websockets
  cocemfe_sevilla/chat_messages/consumers.py
  cocemfe_sevilla/chat_messages/routing.py
  cocemfe_sevilla/chat_messages/templates/chatPage.html
  cocemfe_sevilla/chat_messages/urls.py
  cocemfe_sevilla/chat_messages/views.py
  cocemfe_sevilla/cocemfe_sevilla/asgi.py
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/documents/urls.py
  cocemfe_sevilla/professionals/templates/list_chats.html
  cocemfe_sevilla/requirements.txt
  cocemfe_sevilla/static/css/chat.css
Labels: bug, Grupo 3
