Repository ISPP-Grupo-10/cocemfe-sevilla, pull requests merged in 2024-03, with the labels that each got.

#69 Sprint1 frontend modificar documentos
  codenfe_sevilla/documents/templates/update_pdf.html
Labels: Grupo 4

#78 conf: time zone a española
  codenfe_sevilla/codenfe_sevilla/settings.py
Labels: configuration, Grupo 2

#72 feat: buscador de documentos con filtros
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/documents/templates/docsList.html
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/documents/views.py
  cocemfe_sevilla/static/css/docsList.css
  codenfe_sevilla/documents/migrations/0001_initial.py
  codenfe_sevilla/documents/migrations/0002_remove_document_path_document_pdf_file.py
Labels: feature, Grupo 2

#80 add CI Closes #51
  .github/workflows/django.yml
Labels: configuration

#94 feat: Chat en documentos
  cocemfe_sevilla/chat_messages/admin.py
  cocemfe_sevilla/chat_messages/forms.py
  cocemfe_sevilla/chat_messages/models.py
  cocemfe_sevilla/chat_messages/templates/list_comments.html
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/documents/urls.py
  cocemfe_sevilla/documents/views.py
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/static/css/chat.css
  codenfe_sevilla/documents/migrations/0001_initial.py
  codenfe_sevilla/documents/migrations/0002_remove_document_path_document_pdf_file.py
Labels: feature, Grupo 3

#141 Feature/109 nuevo enumerate documento
  cocemfe_sevilla/documents/models.py
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/documents/views.py
Labels: feature, Grupo 2

#145 Feature/131 Nueva estética página web
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/documents/forms.py
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/documents/templates/upload_pdf.html
  cocemfe_sevilla/documents/views.py
  cocemfe_sevilla/media/pdfs/Jaime_García_García_-_Compromiso_de_Participación_en_la_asignatura_ISPP_v1.3.pdf
  cocemfe_sevilla/media/pdfs/Proyecto_de_laboratorio_de_JavaPOO.pdf
  cocemfe_sevilla/organizations/templates/create_organization.html
  cocemfe_sevilla/organizations/templates/organizations_list.html
  cocemfe_sevilla/organizations/templates/update_organization.html
  cocemfe_sevilla/professionals/templates/professional_list.html
  cocemfe_sevilla/requirements.txt
  cocemfe_sevilla/static/logo_sevilla.png
Labels: feature

#157 #156 Corrige la edición de documentos
  cocemfe_sevilla/documents/templates/update_pdf.html
  cocemfe_sevilla/documents/views.py
Labels: bug

#155 Feature/153 arreglo test documentos
  cocemfe_sevilla/documents/models.py
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/documents/views.py
Labels: bug, test, Grupo 2

#143 Feature/116 and 118_Sprint2_login
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/base/views.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
  cocemfe_sevilla/documents/tests.py
  cocemfe_sevilla/documents/views.py
  cocemfe_sevilla/organizations/views.py
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/models.py
  cocemfe_sevilla/professionals/templates/create_request.html
  cocemfe_sevilla/professionals/templates/list_requests.html
  cocemfe_sevilla/professionals/templates/professional_list.html
  cocemfe_sevilla/professionals/templates/registration/login.html
  cocemfe_sevilla/professionals/templates/registration/signup.html
  cocemfe_sevilla/professionals/templates/update_request.html
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
Labels: feature

#177 Merge de aportaciones a votaciones
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/documents/templates/view_pdf.html
Labels: bug

#179 Feature/166 feature creación profesional frontend (Hacia develop)
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/organizations/templates/organizations_list.html
  cocemfe_sevilla/professionals/templates/professional_create.html
  cocemfe_sevilla/professionals/templates/professional_list.html
Labels: feature, Grupo 3

#182 Hotfix/180 bug las vistas del estado borrador no aparecen
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/documents/views.py
Labels: Grupo 4

#184 feat: Notificacion al crear profesional y varias mejoras
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/professionals/forms.py
  cocemfe_sevilla/professionals/templates/email/new_professional_notification.txt
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
Labels: feature, Grupo 2

#206 fix: corrige edicion de documentos y aparecen profesionales selccionados
  cocemfe_sevilla/documents/templates/update_pdf.html
  cocemfe_sevilla/documents/views.py
Labels: bug, Grupo 4

#207 fix: nueva estetica pagina web
  cocemfe_sevilla/base/templates/base.html
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/organizations/templates/organizations_list.html
  cocemfe_sevilla/organizations/views.py
  cocemfe_sevilla/professionals/templates/create_request.html
  cocemfe_sevilla/professionals/templates/list_chats.html
  cocemfe_sevilla/professionals/templates/list_requests.html
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/professionals/templates/registration/login.html
  cocemfe_sevilla/professionals/urls.py
  cocemfe_sevilla/professionals/views.py
Labels: URGENTE

#200 feat: customer agreement subido
  cocemfe_sevilla/base/templates/index.html
  cocemfe_sevilla/base/templates/politica_terminos.html
  cocemfe_sevilla/base/urls.py
  cocemfe_sevilla/media/other_documents/CustomerAgreement-EN-COCEMFE.pdf
  cocemfe_sevilla/media/other_documents/CustomerAgreement-ES-COCEMFE.pdf
  cocemfe_sevilla/media/other_documents/PolíticasdePrivacidad-COCEMFE.pdf
  cocemfe_sevilla/media/other_documents/PrivacyPolitics-COCEMFE.pdf
Labels: documentation, feature
