Repository ISPP-Grupo-10/cocemfe-sevilla, pull requests merged in 2024-05, with the labels that each got.

#323 feat: Implementadas pantallas de error #Closes #322
  cocemfe_sevilla/base/templates/404.html
  cocemfe_sevilla/base/templates/500.html
  cocemfe_sevilla/base/views.py
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
Labels: configuration, Grupo 3

#319 feat: Añadido frontend de chats.
  cocemfe_sevilla/chat_messages/consumers.py
  cocemfe_sevilla/chat_messages/templates/chatPage.html
  cocemfe_sevilla/chat_messages/views.py
  cocemfe_sevilla/static/css/chat.css
Labels: feature, Grupo 3

#350 fix: Arreglo vistas, botones etc..
  cocemfe_sevilla/base/templates/user_dashboard.html
  cocemfe_sevilla/calendars/templates/create_event.html
  cocemfe_sevilla/documents/templates/list_pdf.html
  cocemfe_sevilla/documents/templates/view_pdf.html
  cocemfe_sevilla/media/pdfs/Daniel_Cortés_Fonseca_-_Compromiso_de_Participación_en_la_asignatura_ISPP_v1.6.pdf
  cocemfe_sevilla/organizations/templates/organizations_list.html
  cocemfe_sevilla/professionals/templates/list_chats.html
  cocemfe_sevilla/professionals/templates/list_requests.html
  cocemfe_sevilla/professionals/templates/professional_detail.html
  cocemfe_sevilla/professionals/templates/professional_list.html
Labels: bug

#338 feat: add calendar tests
  cocemfe_sevilla/calendars/tests.py
Labels: test, Grupo 2

#348 Feature/322 implementar pantallas de error
  cocemfe_sevilla/base/middleware.py
  cocemfe_sevilla/base/views.py
  cocemfe_sevilla/cocemfe_sevilla/settings.py
  cocemfe_sevilla/cocemfe_sevilla/urls.py
Labels: bug, Grupo 3

#358 hotfix: bug 403 parcheado
  cocemfe_sevilla/documents/models.py
  cocemfe_sevilla/maps/views.py
Labels: bug
