Repository ISPP-Grupo-10/cocemfe-sevilla, pull requests merged in 2024-02, with the labels that each got.

#57 base created
  .gitignore
  codenfe_sevilla/base/admin.py
  codenfe_sevilla/base/apps.py
  codenfe_sevilla/base/models.py
  codenfe_sevilla/base/templates/base.html
  codenfe_sevilla/base/templates/index.html
  codenfe_sevilla/base/tests.py
  codenfe_sevilla/base/urls.py
  codenfe_sevilla/base/views.py
  codenfe_sevilla/codenfe_sevilla/settings.py
  codenfe_sevilla/codenfe_sevilla/urls.py
  codenfe_sevilla/media/logo.jpg
  codenfe_sevilla/organizations/admin.py
  codenfe_sevilla/organizations/apps.py
  codenfe_sevilla/organizations/models.py
  codenfe_sevilla/organizations/templates/create_organization.html
  codenfe_sevilla/organizations/tests.py
  codenfe_sevilla/organizations/views.py
  codenfe_sevilla/professionals/models.py
  codenfe_sevilla/requirements.txt
  codenfe_sevilla/static/css/uikit-rtl.css
  codenfe_sevilla/static/css/uikit-rtl.min.css
  codenfe_sevilla/static/css/uikit.css
  codenfe_sevilla/static/css/uikit.min.css
  codenfe_sevilla/static/js/jquery.min.js
  codenfe_sevilla/static/js/uikit-icons.js
  codenfe_sevilla/static/js/uikit-icons.min.js
  codenfe_sevilla/static/js/uikit.js
  codenfe_sevilla/static/js/uikit.min.js
Labels: feature

#68 Feat: Añadida la interfaz para la subida de pdfs
  .gitignore
  codenfe_sevilla/documents/templates/upload_pdf.html
  codenfe_sevilla/documents/views.py
  codenfe_sevilla/organizations/migrations/__init__.py
  codenfe_sevilla/professionals/migrations/__init__.py
Labels: feature, Grupo 4

#60 Añade contraseñas seguras a Professional
  codenfe_sevilla/codenfe_sevilla/settings.py
  codenfe_sevilla/professionals/models.py
  codenfe_sevilla/professionals/validators.py
Labels: feature, configuration, Grupo 3
